title: Tannu Sree Rajput
description:  Highly motivated and results- oriented MSc student in Molecular Biology and Biotechnology student with a
 strong work ethic looking for an internship to put my knowledge and abilities to use in research. aligning with
 my interests mRNA stability, gene regulation, bioremediation, and cell and developmental biology.
 Possesses strong foundation in Molecular Biology techniques. 
#show_downloads: true
theme: jekyll-theme-minimal
