title: Tannu Sree Rajput
#logo: /asserts/img/C:\Users\Tanu sree rajput\OneDrive\Desktop\new_website\tanusreephoto.jpg
#description: Bitchnology student
#show_downloads: true
theme: jekyll-theme-minimal
