title: Tannu Sree Rajput
description: Highly motivated and results-oriented MSc student in Molecular Biology and Biotechnology student with a
strong work ethic looking for an internship to put my knowledge and abilities to use in research.
#show_downloads: true
theme: jekyll-theme-minimal
